"""Label-free authorization and resume guards for full confirmation runs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
import subprocess
from typing import Any, Mapping, Sequence

from .aggregate_benchmark import (
    MAIN_TRAJECTORY,
    PAPER_REFERENCE_SOURCE,
    PAPER_REPORTED_VUS_PR,
)
from .artifacts import verify_committed_score
from .benchmark_manifest import EXPECTED_TRACK_COUNTS, load_benchmark_series
from .config import load_protocol
from .schemas import CheckpointKind, Trajectory, make_run_id, scored_checkpoints
from .vendor import verify_vendor_repo

_DECISION_SCHEMA = "paano-full-benchmark-decision-v1"
_SCORE_SCHEMA = "paano-k0-score-v1"
_CONFIRMATION_SEEDS = (2028, 2029)


def _read_object(path: Path) -> dict[str, Any]:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"JSON payload must be an object: {path}")
    return payload


def _require_equal(observed: object, expected: object, field: str) -> None:
    if observed != expected:
        raise ValueError(
            f"confirmation authorization mismatch for {field}: "
            f"observed={observed!r}, expected={expected!r}"
        )


def _assert_vendor_has_no_semantic_changes(fingerprint: object) -> None:
    """Allow generated bytecode only; reject tracked or source-level drift."""

    root = Path(getattr(fingerprint, "root")).resolve(strict=True)

    def git_paths(*args: str) -> list[str]:
        output = subprocess.run(
            ["git", "-C", str(root), *args, "-z"],
            check=True,
            capture_output=True,
        ).stdout
        return [
            value.decode("utf-8", errors="surrogateescape")
            for value in output.split(b"\0")
            if value
        ]

    tracked = git_paths("diff", "HEAD", "--name-only")
    # Deliberately omit --exclude-standard: ignored untracked source can still
    # affect imports and must not bypass the confirmation source binding.
    untracked = git_paths("ls-files", "--others")
    semantic_untracked = []
    for value in untracked:
        path = PurePosixPath(value)
        candidate = root.joinpath(*path.parts)
        allowed_bytecode = (
            not path.is_absolute()
            and ".." not in path.parts
            and path.parent.name == "__pycache__"
            and path.suffix == ".pyc"
            and candidate.is_file()
            and not any(
                root.joinpath(*path.parts[:index]).is_symlink()
                for index in range(1, len(path.parts) + 1)
            )
        )
        if not allowed_bytecode:
            semantic_untracked.append(value)
    if tracked or semantic_untracked:
        raise ValueError(
            "confirmation vendor checkout contains semantic changes: "
            f"tracked={tracked[:5]}, untracked={semantic_untracked[:5]}"
        )


def validate_confirmation_authorization(
    config_path: Path, vendor_root: Path, decision_path: Path
) -> Mapping[str, Any]:
    """Bind a positive decision to the current frozen protocol and vendor."""

    protocol = load_protocol(Path(config_path))
    fingerprint = verify_vendor_repo(Path(vendor_root), protocol.baseline.git_sha)
    _assert_vendor_has_no_semantic_changes(fingerprint)
    decision = _read_object(Path(decision_path))
    required = {
        "schema_version": _DECISION_SCHEMA,
        "outcome": "CONTINUE_FULL_CONFIRMATION",
        "main_trajectory": MAIN_TRAJECTORY.value,
        "checkpoint": CheckpointKind.LAST.value,
        "paper_reference_type": "external_paper_reported",
        "paper_reference_source": PAPER_REFERENCE_SOURCE,
        "success_requires_both_tracks": True,
        "both_tracks_exceed": True,
        "conditional_confirmation_seeds": list(_CONFIRMATION_SEEDS),
        "seed": 2027,
        "series_count": sum(EXPECTED_TRACK_COUNTS.values()),
        "metric_count": sum(EXPECTED_TRACK_COUNTS.values()) * 3,
        "missing_count": 0,
        "config_sha256": protocol.source_sha256,
        "vendor_sha": protocol.baseline.git_sha,
    }
    for field, expected in required.items():
        if field not in decision:
            raise ValueError(f"confirmation decision is missing field: {field}")
        _require_equal(decision[field], expected, field)

    paper = decision.get("paper_reported_vus_pr")
    if not isinstance(paper, dict) or set(paper) != set(PAPER_REPORTED_VUS_PR):
        raise ValueError("confirmation decision paper references must be exactly U and M")
    for track, expected in PAPER_REPORTED_VUS_PR.items():
        if track not in paper or float(paper[track]) != expected:
            raise ValueError(f"confirmation paper reference changed for track {track}")

    tracks = decision.get("tracks")
    if not isinstance(tracks, dict) or set(tracks) != set(EXPECTED_TRACK_COUNTS):
        raise ValueError("confirmation decision must contain exactly U and M tracks")
    for track, expected_files in EXPECTED_TRACK_COUNTS.items():
        item = tracks[track]
        if not isinstance(item, dict):
            raise ValueError(f"confirmation decision track {track} must be an object")
        _require_equal(item.get("track"), track, f"tracks.{track}.track")
        _require_equal(item.get("files"), expected_files, f"tracks.{track}.files")
        _require_equal(
            item.get("exceeds_paper_reported"),
            True,
            f"tracks.{track}.exceeds_paper_reported",
        )
    return decision


def validate_existing_confirmation_run(
    config_path: Path,
    manifest_path: Path,
    vendor_root: Path,
    output_root: Path,
    series_id: str,
    seed: int,
    trajectory: Trajectory | str = MAIN_TRAJECTORY,
) -> Path:
    """Verify an existing confirmation result before a resume skip."""

    if seed not in _CONFIRMATION_SEEDS:
        raise ValueError("confirmation resume seed is not registered")
    trajectory = Trajectory(trajectory)
    if trajectory is not MAIN_TRAJECTORY:
        raise ValueError("confirmation resume trajectory is not registered")
    protocol = load_protocol(Path(config_path))
    protocol.trajectory(trajectory)
    fingerprint = verify_vendor_repo(Path(vendor_root), protocol.baseline.git_sha)
    _assert_vendor_has_no_semantic_changes(fingerprint)
    spec = load_benchmark_series(Path(manifest_path), series_id)
    trajectory_dir = (
        Path(output_root)
        / "runs"
        / spec.series_id
        / f"seed_{seed}"
        / trajectory.value
    )
    failure_path = trajectory_dir / "_FAILED.json"
    if failure_path.is_file():
        raise ValueError(f"retained failure blocks confirmation resume: {failure_path}")
    marker_path = trajectory_dir / "_SUCCESS"
    if not marker_path.is_file():
        raise FileNotFoundError(f"missing trajectory success marker: {marker_path}")
    expected_marker = f"{spec.series_id} seed={seed} trajectory={trajectory.value}"
    if marker_path.read_text(encoding="ascii").strip() != expected_marker:
        raise ValueError("trajectory success marker identity mismatch")

    score_dir = trajectory_dir / "scores" / CheckpointKind.LAST.value
    scores, manifest = verify_committed_score(score_dir)
    hp = protocol.official_hyperparameters
    expected_manifest = {
        "schema_version": _SCORE_SCHEMA,
        "run_id": make_run_id(spec.series_id, seed, trajectory, CheckpointKind.LAST),
        "series_id": spec.series_id,
        "family": spec.family,
        "track": spec.track,
        "data_sha256": spec.csv_sha256,
        "config_sha256": protocol.source_sha256,
        "vendor_sha": protocol.baseline.git_sha,
        "seed": seed,
        "trajectory": trajectory,
        "checkpoint": CheckpointKind.LAST,
        "num_points": spec.rows,
        "channels": spec.channels,
        "patch_size": hp.patch_size,
        "stride": hp.stride,
        "top_k": hp.score_top_k,
    }
    for field, expected in expected_manifest.items():
        observed = getattr(manifest, field)
        if observed != expected:
            raise ValueError(
                f"confirmation score manifest mismatch for {field}: "
                f"observed={observed!r}, expected={expected!r}"
            )
    if scores.shape != (spec.rows,):
        raise ValueError("confirmation score length differs from manifest series")

    summary_path = trajectory_dir / "training_summary.json"
    if not summary_path.is_file():
        raise FileNotFoundError(f"missing confirmation training summary: {summary_path}")
    summary = _read_object(summary_path)
    expected_summary = {
        "series_id": spec.series_id,
        "family": spec.family,
        "track": spec.track,
        "seed": seed,
        "trajectory": trajectory.value,
        "data_sha256": spec.csv_sha256,
        "config_sha256": protocol.source_sha256,
        "vendor_sha": protocol.baseline.git_sha,
        "scored_checkpoints": [item.value for item in scored_checkpoints(trajectory)],
        "initial_state_sha256": manifest.initial_state_sha256,
        "replay_sha256": manifest.replay_sha256,
    }
    for field, expected in expected_summary.items():
        if field not in summary:
            raise ValueError(f"confirmation training summary is missing field: {field}")
        if summary[field] != expected:
            raise ValueError(f"confirmation training summary mismatch for {field}")
    if not isinstance(summary.get("vendor_dirty"), bool):
        raise ValueError("confirmation training summary vendor_dirty must be boolean")
    checkpoint_shas = summary.get("checkpoint_sha256")
    if not isinstance(checkpoint_shas, dict) or (
        checkpoint_shas.get(CheckpointKind.LAST.value) != manifest.checkpoint_sha256
    ):
        raise ValueError("confirmation LAST checkpoint identity mismatch")
    return trajectory_dir


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    authorize = subparsers.add_parser("authorize")
    authorize.add_argument("--config", type=Path, required=True)
    authorize.add_argument("--vendor-root", type=Path, required=True)
    authorize.add_argument("--decision", type=Path, required=True)

    validate = subparsers.add_parser("validate-run")
    validate.add_argument("--config", type=Path, required=True)
    validate.add_argument("--manifest", type=Path, required=True)
    validate.add_argument("--vendor-root", type=Path, required=True)
    validate.add_argument("--output-root", type=Path, required=True)
    validate.add_argument("--series-id", required=True)
    validate.add_argument("--seed", type=int, required=True)
    validate.add_argument(
        "--trajectory",
        choices=(MAIN_TRAJECTORY.value,),
        default=MAIN_TRAJECTORY.value,
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if args.command == "authorize":
        validate_confirmation_authorization(args.config, args.vendor_root, args.decision)
        print("FULL_CONFIRMATION_AUTHORIZATION_VALIDATED")
        return 0
    validate_existing_confirmation_run(
        args.config,
        args.manifest,
        args.vendor_root,
        args.output_root,
        args.series_id,
        args.seed,
        args.trajectory,
    )
    print(
        "FULL_CONFIRMATION_RUN_VALIDATED "
        f"series={args.series_id} seed={args.seed} trajectory={args.trajectory}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
